# Generated by Django 3.1.3 on 2020-11-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('publish_year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('isbn_10', models.CharField(blank=True, max_length=10, null=True)),
                ('isbn_13', models.CharField(blank=True, max_length=13, null=True)),
                ('oclc_number', models.CharField(blank=True, max_length=25, null=True)),
                ('lccn_number', models.CharField(blank=True, max_length=25, null=True)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('cover', models.URLField(blank=True)),
                ('language', models.CharField(max_length=2)),
                ('subject', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
