# Generated by Django 3.1.3 on 2020-11-03 21:06

import book_manager.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('publish_year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('isbn', models.CharField(max_length=13, validators=[book_manager.validators.validate_isbn_type])),
                ('pages', models.PositiveIntegerField()),
                ('cover', models.URLField()),
                ('language', models.CharField(max_length=2)),
            ],
        ),
    ]
